### ISSUE TITLE
azk not start on mac ( Cannot start container)

### ISSUE THREAD

**Issue by lcsbaroni** [azukiapp/azk#197]
When I try start azk on mac, I get the error bellow, but if run the same azkfile on ubuntu, it's work.

```shell
azk: Error: HTTP code is 500 which indicates error: server error - Cannot start container 012350e28f4e07e0854d33d58ff59d12ea6bc292bfa3579a024891c50a29a708: exec: "/bin/bash": stat /bin/bash: no such file or directory
azk:     at [object Object].Modem.buildPayload (/usr/local/Cellar/azk/0.7.1/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:157:15)
azk:     at IncomingMessage.<anonymous> (/usr/local/Cellar/azk/0.7.1/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:133:14)
azk:     at IncomingMessage.emit (events.js:117:20)
azk:     at _stream_readable.js:943:16
azk: From previous event:
azk:     at Container._.each.newClass.(anonymous function) [as start] (/azk.io:0.7.1/src/utils/index.js:103:38)
azk:     at Docker.<anonymous> (/azk.io:0.7.1/src/docker/run.js:136:19)
azk:     at eval (eval at <anonymous> (/usr/local/Cellar/azk/0.7.1/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:589:32)
azk:     at nextOrThrow (eval at <anonymous> (/usr/local/Cellar/azk/0.7.1/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:496:21)
azk:     at GeneratorFunctionPrototype.next (eval at <anonymous> (/usr/local/Cellar/azk/0.7.1/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:516:14)
```

**Comment by nuxlli** [comment]
@lcsbaroni refactoring solution proposed by @gullitmiranda solve your problem?

**Comment by lcsbaroni** [comment]
Yes!! Thanks a lot!

**Comment by nuxlli** [comment]
Us is that we appreciate, and we are always available.
