### ISSUE TITLE
SFTP issue breaking agent. 

### ISSUE THREAD

**Issue by jturolla** [azukiapp/azk#208]
SFTP error when initiating agent after v0.8 upgrade. 

```javascript
azk: Upload the ssh key to vm...
azk: status.vm.docker_keys
azk: Agent starting error: Error: No such file
azk:     at SFTP._parse (/usr/local/Cellar/azk/0.8.0/node_modules/ssh2/lib/SFTP/SFTPv3.js:967:23)
azk:     at ChannelStream.<anonymous> (/usr/local/Cellar/azk/0.8.0/node_modules/ssh2/lib/SFTP/SFTPv3.js:49:12)
azk:     at ChannelStream.emit [as _emit] (events.js:95:17)
azk:     at ChannelStream.emit (/usr/local/Cellar/azk/0.8.0/node_modules/ssh2/lib/Channel.js:609:12)
azk:     at Parser.<anonymous> (/usr/local/Cellar/azk/0.8.0/node_modules/ssh2/lib/Channel.js:95:20)
azk:     at Parser.emit (events.js:95:17)
azk:     at Parser.parsePacket (/usr/local/Cellar/azk/0.8.0/node_modules/ssh2/lib/Parser.js:596:12)
azk:     at Parser.execute (/usr/local/Cellar/azk/0.8.0/node_modules/ssh2/lib/Parser.js:249:14)
azk:     at Socket.<anonymous> (/usr/local/Cellar/azk/0.8.0/node_modules/ssh2/lib/Connection.js:515:18)
azk:     at Socket.emit (events.js:95:17)
azk: From previous event:
azk:     at Utils.defer (/azk.io:0.8.0/src/utils/index.js:59:12)
azk:     at execute (/azk.io:0.8.0/src/agent/ssh.js:76:14)
azk:     at SSH.connect (/azk.io:0.8.0/src/agent/ssh.js:106:14)
azk:     at SSH.getFile (/azk.io:0.8.0/src/agent/ssh.js:37:15)
azk:     at /azk.io:0.8.0/src/agent/vm.js:337:57
azk: From previous event:
azk:     at Object.vm.copyVMFile (/azk.io:0.8.0/src/agent/vm.js:337:30)
azk:     at Object.<anonymous> (/azk.io:0.8.0/src/agent/server.js:117:18)
azk:     at eval (eval at <anonymous> (/usr/local/Cellar/azk/0.8.0/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:589:32)
azk:     at nextOrThrow (eval at <anonymous> (/usr/local/Cellar/azk/0.8.0/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:496:21)
azk:     at GeneratorFunctionPrototype.next (eval at <anonymous> (/usr/local/Cellar/azk/0.8.0/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:516:14).
azk: Agent is being stopped...
azk: Stopping virtual machine...
azk: Virtual machine has been successfully stopped.
azk: Agent has been successfully stopped.
```

**Comment by lucasfais** [comment]
Hey @jturolla, sorry for the delay to answer this issue.

That problem is fixed in version **v0.8.2 or later**. So, try to upgrade your azk installation.

I will close this issue for now, but feel free to reopen it if the problem persists.
