### ISSUE TITLE
[docs] Missing example in 4.2 azk configs

### ISSUE THREAD

**Issue by gullitmiranda** [azukiapp/azk#241]
Moved of: [azukiapp/azk-docs-deprecated#4](https://github.com/azukiapp/azk-docs-deprecated/issues/4)

**Comment by saitodisse** [comment]
When I tried to run this command I saw this error:

```
$ azk configs

azk: Error: Config docker:host to be set by configure
azk:     at get (/azk.io:0.9.2/src/config.js:168:11)
azk:     at Cmd.action (/azk.io:0.9.2/src/cmds/configs.js:7:19)
azk:     at Cmd.before_action (/azk.io:0.9.2/src/cli/command.js:210:15)
azk:     at Cmd.run (/azk.io:0.9.2/src/cli/command.js:214:15)
azk:     at CmdCli.action (/azk.io:0.9.2/src/cli/cli.js:64:16)
azk:     at Object.superCall (eval at <anonymous> (/home/julio/_git/azk/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:310:45)
azk:     at CmdCli.action (/azk.io:0.9.2/@traceur/generated/TemplateParser/23:1:15)
azk:     at CmdCli.before_action (/azk.io:0.9.2/src/cli/command.js:210:15)
azk:     at CmdCli.run (/azk.io:0.9.2/src/cli/command.js:214:15)
azk:     at cli (/azk.io:0.9.2/src/cli/index.js:45:20)
azk: From previous event:
azk:     at cli (/azk.io:0.9.2/src/cli/index.js:52:10)
azk:     at Object.<anonymous> (/home/julio/_git/azk/bin/azk.js:34:1)

```

**Comment by saitodisse** [comment]
this is an old deprecated feature.
