### ISSUE TITLE
[Dockerfile] Azk fails when `Dockerfile` fails

### ISSUE THREAD

**Issue by lucasfais** [azukiapp/azk#303]
When specifying a `Dockerfile` that fails to build:

```dockerfile
FROM fedora:latest

RUN exit 1000
```

The user receives the output below:

```shell
$ azk shell -vvvv
azk: ⇲ building `azkbuild/d61536e9ed-api:6651ddff6eb82c840ced7c1dddee15c6e1913dd4` image...
  Step 0 : FROM fedora:latest
   ---> 834629358fe2
  Step 1 : RUN exit 1000
   ---> Running in 739c02106659
  Removing intermediate container 739c02106659
azk: TypeError: Cannot call method 'inspect' of null
azk:     at /azk.io:0.10.2/src/system/run.js:292:18
azk:     at eval (eval at <anonymous> (/Users/lucasfais/Dropbox/Workspace/Azuki/azk/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:589:32)
azk:     at nextOrThrow (eval at <anonymous> (/Users/lucasfais/Dropbox/Workspace/Azuki/azk/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:496:21)
azk:     at GeneratorFunctionPrototype.next (eval at <anonymous> (/Users/lucasfais/Dropbox/Workspace/Azuki/azk/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:516:14)
azk: From previous event:
azk:     at Object._onImmediate (/azk.io:0.10.2/src/utils/index.js:72:16)
azk:     at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by saitodisse** [comment]
:+1: inspect call must be fail safe.
