### ISSUE TITLE
Docker not available

### ISSUE THREAD

**Issue by dynaum** [azukiapp/azk#305]
Today when I tried to start the azk agent:

```shell
? The agent is not running, would you like to start it? Yes
azk: Wait, this process may take several minutes
azk: Loading settings and checking dependencies.
azk: Settings loaded successfully.
azk: Removing virtual machine...
azk: Error in vm process: Error: command: storagectl azk-vm-dev.azk.io --name SATA --remove
azk: VBoxManage: error: The machine is not mutable (state is Saved)
azk: VBoxManage: error: Details: code VBOX_E_INVALID_VM_STATE (0x80bb0002), component SessionMachine, interface IMachine, callee nsISupports
azk: VBoxManage: error: Context: "RemoveStorageController(Bstr(pszCtl).raw())" at line 1026 of file VBoxManageStorageController.cpp
azk:     at /azk.io:0.10.1/src/agent/vm.js:19:13
azk: From previous event:
azk:     at exec (/azk.io:0.10.1/@traceur/generated/TemplateParser/18:1:41)
azk:     at Object.<anonymous> (/azk.io:0.10.1/src/agent/vm.js:408:17)
azk:     at eval (eval at <anonymous> (/usr/local/Cellar/azk/0.10.1/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:589:32)
azk:     at nextOrThrow (eval at <anonymous> (/usr/local/Cellar/azk/0.10.1/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:496:21)
azk:     at GeneratorFunctionPrototype.next (eval at <anonymous> (/usr/local/Cellar/azk/0.10.1/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:516:14)
azk: Error in vm process: Error: command: closemedium disk /Users/dynaum/.azk/data/vm/azk-agent.vmdk
azk: VBoxManage: error: Medium '/Users/dynaum/.azk/data/vm/azk-agent.vmdk' cannot be closed because it is still attached to 1 virtual machines
azk: VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component Medium, interface IMedium, callee nsISupports
azk: VBoxManage: error: Context: "Close()" at line 1349 of file VBoxManageDisk.cpp
azk:     at /azk.io:0.10.1/src/agent/vm.js:19:13
azk: From previous event:
azk:     at exec (/azk.io:0.10.1/@traceur/generated/TemplateParser/18:1:41)
azk:     at Object.<anonymous> (/azk.io:0.10.1/src/agent/vm.js:409:17)
azk:     at eval (eval at <anonymous> (/usr/local/Cellar/azk/0.10.1/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:589:32)
azk:     at nextOrThrow (eval at <anonymous> (/usr/local/Cellar/azk/0.10.1/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:496:21)
azk:     at GeneratorFunctionPrototype.next (eval at <anonymous> (/usr/local/Cellar/azk/0.10.1/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:516:14)
azk: Virtual machine has been successfully removed.
```

And now the agent do not start again:

```shell
azk: Shared folder has been successfully mounted.
azk: Trying to connect to docker (http://192.168.50.4:2375) (1/10)...
azk: Trying to connect to docker (http://192.168.50.4:2375) (2/10)...
azk: Trying to connect to docker (http://192.168.50.4:2375) (3/10)...
azk: Trying to connect to docker (http://192.168.50.4:2375) (4/10)...
azk: Trying to connect to docker (http://192.168.50.4:2375) (5/10)...
azk: Trying to connect to docker (http://192.168.50.4:2375) (6/10)...
azk: Trying to connect to docker (http://192.168.50.4:2375) (7/10)...
azk: Trying to connect to docker (http://192.168.50.4:2375) (8/10)...
azk: Trying to connect to docker (http://192.168.50.4:2375) (9/10)...
azk: Trying to connect to docker (http://192.168.50.4:2375) (10/10)...
azk: azk agent start error: Could not initialize balancer because docker was not available
```

**Comment by dynaum** [comment]
```shell
$ azk --version
azk 0.10.2
```

**Comment by dynaum** [comment]
I tried again and worked but I lost my docker images and all gems installed. This is really painful for development.

**Comment by jturolla** [comment]
:+1:

**Comment by jturolla** [comment]
```
➜  gaia git:(sms-batch-messages) azk agent start
azk: Wait, this process may take several minutes
azk: Loading settings and checking dependencies.
azk: Checking version...
azk: Settings loaded successfully.
azk: Removing virtual machine...
azk: Error in vm process: Error: command: storagectl azk-vm-dev.azk.io --name SATA --remove
azk: VBoxManage: error: The machine is not mutable (state is Saved)
azk: VBoxManage: error: Details: code VBOX_E_INVALID_VM_STATE (0x80bb0002), component SessionMachine, interface IMachine, callee nsISupports
azk: VBoxManage: error: Context: "RemoveStorageController(Bstr(pszCtl).raw())" at line 1026 of file VBoxManageStorageController.cpp
azk:     at /azk.io:0.10.2/src/agent/vm.js:19:13
azk: From previous event:
azk:     at exec (/azk.io:0.10.2/@traceur/generated/TemplateParser/18:1:41)
azk:     at Object.<anonymous> (/azk.io:0.10.2/src/agent/vm.js:408:17)
azk:     at eval (eval at <anonymous> (/usr/local/Cellar/azk/0.10.2/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:589:32)
azk:     at nextOrThrow (eval at <anonymous> (/usr/local/Cellar/azk/0.10.2/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:496:21)
azk:     at GeneratorFunctionPrototype.next (eval at <anonymous> (/usr/local/Cellar/azk/0.10.2/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:516:14)
azk: Error in vm process: Error: command: closemedium disk /Users/jturolla/.azk/data/vm/azk-agent.vmdk
azk: VBoxManage: error: Medium '/Users/jturolla/.azk/data/vm/azk-agent.vmdk' cannot be closed because it is still attached to 1 virtual machines
azk: VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component Medium, interface IMedium, callee nsISupports
azk: VBoxManage: error: Context: "Close()" at line 1349 of file VBoxManageDisk.cpp
azk:     at /azk.io:0.10.2/src/agent/vm.js:19:13
azk: From previous event:
azk:     at exec (/azk.io:0.10.2/@traceur/generated/TemplateParser/18:1:41)
azk:     at Object.<anonymous> (/azk.io:0.10.2/src/agent/vm.js:409:17)
azk:     at eval (eval at <anonymous> (/usr/local/Cellar/azk/0.10.2/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:589:32)
azk:     at nextOrThrow (eval at <anonymous> (/usr/local/Cellar/azk/0.10.2/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:496:21)
azk:     at GeneratorFunctionPrototype.next (eval at <anonymous> (/usr/local/Cellar/azk/0.10.2/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:516:14)
azk: Virtual machine has been successfully removed.
azk: Agent is being started...
azk: Installing virtual machine...
azk: Virtual machine has been successfully installed.
azk: Setting the ssh key to vm...
azk: Starting virtual machine...
azk: Waiting for virtual machine boot...
azk: Virtual machine is ready to use.
azk: Mounting the shared folder in virtual machine...
azk: Shared folder has been successfully mounted.
azk: Trying to connect to docker (http://192.168.50.4:2375) (1/10)...
azk: Starting azk dns service...
azk: Dns service started.
azk: Trying to connect to docker (http://192.168.50.4:2375) (1/10)...
azk: Starting azk balancer redirect service...
azk: Check if balancer redirect service is up (tcp://192.168.50.4:80) (1/10)...
azk: Balancer redirect started.
azk: Starting memcached service...
azk: Memcached service started.
azk: Starting http balancer service...
azk: Http balancer service started.
azk: Agent has been successfully started.
```

Happened to me again today.

**Comment by jturolla** [comment]
This always happen when restarting the agent after a failure while trying to use `azk shell`.

This is its trace:

```
azk: Error: connect ETIMEDOUT
azk:     at errnoException (net.js:904:11)
azk:     at Object.afterConnect [as oncomplete] (net.js:895:19)
azk: From previous event:
azk:     at Object.Run.instances (/azk.io:0.10.2/src/system/run.js:324:50)
azk:     at System.instances (/azk.io:0.10.2/src/system/index.js:59:33)
azk:     at Object.<anonymous> (/azk.io:0.10.2/src/system/run.js:298:34)
azk:     at eval (eval at <anonymous> (/usr/local/Cellar/azk/0.10.2/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:589:32)
azk:     at nextOrThrow (eval at <anonymous> (/usr/local/Cellar/azk/0.10.2/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:496:21)
azk:     at GeneratorFunctionPrototype.next (eval at <anonymous> (/usr/local/Cellar/azk/0.10.2/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:516:14)
```

**Comment by heitortsergent** [comment]
@dynaum @jturolla we managed to reproduce the error, and should push a hotfix in the next few days.

**Comment by dynaum** [comment]
Nice!

**Comment by jturolla** [comment]
:100:
