### ISSUE TITLE
browser closes without any error message

### ISSUE THREAD

**Issue by saitodisse** [azukiapp/azk#315]
`libnss-resolver` (https://github.com/azukiapp/libnss-resolver) appears to force google chrome and firefox browsers to exit. 

Gives the error bellow when try to hit an address that is configured at `libnss-resolver` folders, like: `/etc/resolver/dev.azk.io` and `azk agent` is down. On opera browser the error does not occurs.

```
Stacktrace:
 #0  0x00007f6c070dd20b in raise (sig=11) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:37
         resultvar = 0
         pid = <optimized out>
 #1  0x00007f6c021b87f0 in ?? () from /usr/lib/firefox/libxul.so
 No symbol table info available.
 #2  <signal handler called>
 No locals.
 #3  0x00007f6bd5df231f in _nss_resolver_gethostbyname2_r () from /usr/lib/libnss_resolver.so.2
 No symbol table info available.
 #4  0x00007f6c065c70a9 in gaih_inet (name=<optimized out>, name@entry=0x7f6bccb61bc0 "azkdemo.dev.azk.io", service=<optimized out>, req=req@entry=0x7f6bc94fed90, pai=pai@entry=0x7f6bc94fec30, naddrs=naddrs@entry=0x7f6bc94fec20) at ../sysdeps/posix/getaddrinfo.c:960
         i = <optimized out>
         herrno = 4
         th = {h_name = 0x7f6c00000001 <error: Não é possível acessar a memória no endereço 0x7f6c00000001>, h_aliases = 0xc066306f1, h_addrtype = 16, h_length = 23610, h_addr_list = 0x0}
         localcanon = 0x0
         h = <optimized out>
         fct = <optimized out>
         fct4 = <optimized out>
         pat = <optimized out>
         no_inet6_data = <optimized out>
         nip = <optimized out>
         status = <optimized out>
         no_more = 0
         old_res_options = <optimized out>
         tmpbuflen = <optimized out>
         no_data = 0
         inet6_status = <optimized out>
         tp = <optimized out>
         st = 0x7f6bc94fe9e0
         at = 0x7f6bc94fe9a0
         rc = 0
         got_ipv6 = <optimized out>
         canon = <optimized out>
         orig_name = 0x7f6bccb61bc0 "azkdemo.dev.azk.io"
         alloca_used = <optimized out>
         port = <optimized out>
         malloc_name = <optimized out>
         malloc_addrmem = false
         addrmem = 0x0
         malloc_canonbuf = <optimized out>
         canonbuf = <optimized out>
         malloc_tmpbuf = false
         tmpbuf = 0x7f6bc94fe560 "\377\002"
         result = 0
 #5  0x00007f6c065c9e0d in __GI_getaddrinfo (name=0x7f6bccb61bc0 "azkdemo.dev.azk.io", service=0x0, hints=0x7f6bc94fed90, pai=0x7f6bc94fed88) at ../sysdeps/posix/getaddrinfo.c:2406
         i = 0
         last_i = 0
         nresults = 0
         p = 0x0
         gaih_service = {name = 0x0, num = -866578352}
         pservice = <optimized out>
         local_hints = {ai_flags = -917509020, ai_family = 32619, ai_socktype = 0, ai_protocol = 0, ai_addrlen = 1408996995, ai_addr = 0x7f6bc94fed80, ai_canonname = 0x5cd2 <error: Não é possível acessar a memória no endereço 0x5cd2>, ai_next = 0x7f6bc94fee48}
         in6ai = 0x7f6bccb4a4d8
         in6ailen = 5
         seen_ipv4 = true
         seen_ipv6 = true
         check_pf_called = true
         end = 0x7f6bc94fec30
         naddrs = 0
         __PRETTY_FUNCTION__ = "getaddrinfo"
 #6  0x00007f6c05ddd96f in PR_GetAddrInfoByName () from /usr/lib/firefox/libnspr4.so
 No symbol table info available.
 #7  0x00007f6c00f035b4 in ?? () from /usr/lib/firefox/libxul.so
 No symbol table info available.
 #8  0x00007f6c00eff1e4 in ?? () from /usr/lib/firefox/libxul.so
 No symbol table info available.
 #9  0x00007f6c05de9268 in ?? () from /usr/lib/firefox/libnspr4.so
 No symbol table info available.
 #10 0x00007f6c070d5182 in start_thread (arg=0x7f6bc94ff700) at pthread_create.c:312
         __res = <optimized out>
         pd = 0x7f6bc94ff700
         now = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140100915689216, -7712512192341633405, 0, 0, 140100915689920, 140100915689216, 7647171101949924995, 7651520232653166211}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimized out>
         pagesize_m1 = <optimized out>
         sp = <optimized out>
         freesize = <optimized out>
         __PRETTY_FUNCTION__ = "start_thread"
 #11 0x00007f6c065f447d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by fearenales** [comment]
This issue is fixed by [libnss-resolver release v0.3.0](https://github.com/azukiapp/libnss-resolver/releases/tag/v0.3.0).

The [commit 00d5c1d](https://github.com/azukiapp/libnss-resolver/commit/00d5c1d8a1b1a9aee39c4f8ac5dbfca7452159c2) fixes the issue by initializing the allocated memory, avoiding it to point to random memory addresses, which, in most cases, causes the browser to receive a **SIGSEGV** signal.
