### ISSUE TITLE
Error in azk start

### ISSUE THREAD

**Issue by leonciokof** [azukiapp/azk#349]
My system: 
```
Ubuntu 14.04 x64
Docker version 1.5.0, build a8a31ef
azk 0.11.0
```

My Azkfile.js

```js
/**
 * Documentation: http://docs.azk.io/Azkfile.js
 */

// Adds the systems that shape your system
systems({
  'aguas-andinas': {
    // Dependent systems
    depends: ["mongodb"],
    // More images:  http://images.azk.io
    image: {"docker": "azukiapp/node:0.12"},
    // Steps to execute before running instances
    provision: [
      "npm install",
    ],
    workdir: "/azk/#{manifest.dir}",
    shell: "/bin/bash",
    command: "node server/app.js",
    wait: {"retry": 20, "timeout": 1000},
    mounts: {
      '/azk/#{manifest.dir}': path("dist"),
    },
    scalable: {"default": 1},
    http: {
      domains: [ "#{system.name}.#{azk.default_domain}" ]
    },
    envs: {
      // set instances variables
      NODE_ENV: "production",
    },
  },
  mongodb: {
    image : { docker: "azukiapp/mongodb" },
    scalable: false,
    wait: {"retry": 20, "timeout": 1000},
    // Mounts folders to assigned paths
    mounts: {
      // equivalent persistent_folders
      '/data/db': persistent('mongodb-#{manifest.dir}'),
    },
    ports: {
      http: "28017:28017/tcp",
    },
    http      : {
      // aircrm-mongodb.azk.dev
      domains: [ "#{manifest.dir}-#{system.name}.#{azk.default_domain}" ],
    },
    export_envs        : {
      MONGODB_URI: "mongodb://#{net.host}:#{net.port[27017]}/#{manifest.dir}_development",
    },
  },
});
```

Error:
```sh
❯❯❯ azk start -B -R -vv
azk: ↑ starting `mongodb` system, 1 new instances...
azk: ✓ checking `azukiapp/mongodb:latest` image...
azk: Error: HTTP code is 500 which indicates error: server error - Cannot start container e46d51ac229eed27c291a0f025b20af32541ea2d13d132c2e1b588545d0b23f2: exec: "mongod --rest --httpinterface": executable file not found in $PATH
azk:     at [object Object].Modem.buildPayload (/usr/lib/azk/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:202:15)
azk:     at IncomingMessage.<anonymous> (/usr/lib/azk/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:178:14)
azk:     at IncomingMessage.emit (events.js:117:20)
azk:     at _stream_readable.js:944:16
azk: From previous event:
azk:     at Container._.each.newClass.(anonymous function) [as start] (/azk.io:0.11.0/src/utils/index.js:110:38)
azk:     at Docker.<anonymous> (/azk.io:0.11.0/src/docker/run.js:135:19)
azk:     at eval (eval at <anonymous> (/usr/lib/azk/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:589:32)
azk:     at nextOrThrow (eval at <anonymous> (/usr/lib/azk/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:496:21)
azk:     at GeneratorFunctionPrototype.next (eval at <anonymous> (/usr/lib/azk/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:516:14)
azk: Due to the above error azk will stop all instances already running.

azk: System `aguas-andinas` not running
azk: System `mongodb` not running

┌───┬───────────────┬───────────┬──────────────────────────────────┬─────────────────┬─────────────┐
│   │ System        │ Instances │ Hostname/url                     │ Instances-Ports │ Provisioned │
├───┼───────────────┼───────────┼──────────────────────────────────┼─────────────────┼─────────────┤
│ ↓ │ aguas-andinas │ 0         │ aguas-andinas.dev.azk.io         │ -               │ -           │
├───┼───────────────┼───────────┼──────────────────────────────────┼─────────────────┼─────────────┤
│ ↓ │ mongodb       │ 0         │ aguas-andinas-mongodb.dev.azk.io │ -               │ -           │
└───┴───────────────┴───────────┴──────────────────────────────────┴─────────────────┴─────────────┘
```

**Comment by gullitmiranda** [comment]
This issue made me find two problems:

1. `CMD` of image `azukiapp/mongodb` was incorrect.
2. The flag `--pull` to force pull of docker image not working.

### Solutions:

1. I updated the image `azukiapp/mongodb` with [this commit](https://github.com/azukiapp/docker-mongodb/commit/93616029ca8c75110f7fa993fbe3c176d6537bcc).
2. The pull request #350 fix the problem, and is already available in the next release.

For now, you can update the image using docker directly:

```sh
$ adocker pull azukiapp/mongodb
$ azk start -vv -R
```

**Comment by heitortsergent** [comment]
Hey @leonciokof did you manage to workaround the problem and run your project? :)

**Comment by leonciokof** [comment]
I got this error:

```sh
azk: ↑ starting `mongodb` system, 1 new instances...
azk: ✓ checking `azukiapp/mongodb:latest` image...
azk: ◴ waiting for `mongodb` system to start, trying connection to port http/tcp...
azk: Run system `mongodb` return: (0), for command: mongod --rest --httpinterface:
azk: [timeout] `azk` has timed out on `mongodb` system.
azk: [timeout] Failure to reach port `28017` from `http://aguas-andinas-mongodb.dev.azk.io` after 40 attempt[s] of 1000 milliseconds.
azk: [timeout] Make sure the start command binds `port` to the `0.0.0.0` interface, not only to the `localhost` interface.
azk: [timeout] You might want to edit your `Azkfile.js` in order to increase the maximum timeout.
azk: Due to the above error azk will stop all instances already running.

azk: System `aguas-andinas` not running
azk: ↓ stopping `mongodb` system, 1 instances...

┌───────────────┬───────┬──────────────────────────────────┬─────────────────┐
│ System        │ Inst. │ Hostname/url                     │ Instances-Ports │
├───────────────┼───────┼──────────────────────────────────┼─────────────────┤
│ aguas-andinas │ 0     │ aguas-andinas.dev.azk.io         │ -               │
├───────────────┼───────┼──────────────────────────────────┼─────────────────┤
│ mongodb       │ 0     │ aguas-andinas-mongodb.dev.azk.io │ -               │
└───────────────┴───────┴──────────────────────────────────┴─────────────────┘
```

**Comment by gullitmiranda** [comment]
Could put part of your `Azkfile.js` for your system `mongodb`?

**Comment by leonciokof** [comment]
My Azkfile.js

```javascript
/**
 * Documentation: http://docs.azk.io/Azkfile.js
 */

// Adds the systems that shape your system
systems({
  'aguas-andinas': {
    // Dependent systems
    depends: ["mongodb"],
    // More images:  http://images.azk.io
    image: {"docker": "azukiapp/node:0.12"},
    // Steps to execute before running instances
    provision: [
      "npm install",
    ],
    workdir: "/azk/#{manifest.dir}",
    shell: "/bin/bash",
    command: "node server/app.js",
    wait: {"retry": 20, "timeout": 1000},
    mounts: {
      '/azk/#{manifest.dir}': path("dist"),
    },
    scalable: {"default": 1},
    http: {
      domains: [ "#{system.name}.#{azk.default_domain}" ]
    },
    envs: {
      // set instances variables
      NODE_ENV: "production",
    },
  },
  mongodb: {
    image : { docker: "azukiapp/mongodb" },
    scalable: false,
    wait: {"retry": 40, "timeout": 1000},
    // Mounts folders to assigned paths
    mounts: {
      // equivalent persistent_folders
      '/data/db': persistent('mongodb-#{manifest.dir}'),
    },
    ports: {
      http: "28017:28017/tcp",
    },
    http      : {
      // aircrm-mongodb.azk.dev
      domains: [ "#{manifest.dir}-#{system.name}.#{azk.default_domain}" ],
    },
    export_envs        : {
      MONGODB_URI: "mongodb://#{net.host}:#{net.port[27017]}/#{manifest.dir}_development",
    },
  },
});
```

**Comment by gullitmiranda** [comment]
Once it was made attempts using a problematic image, some noise can remain in the persistent data.
To clear it, run the following command:

```
$ azk shell -c 'rm -rf /data/db/*'
```

**Comment by leonciokof** [comment]
I got this error:

```sh
azk: ↑ starting `mongodb` system, 1 new instances...
azk: ✓ checking `azukiapp/mongodb:latest` image...
azk: ◴ waiting for `mongodb` system to start, trying connection to port http/tcp...
azk: ↑ starting `aguas-andinas` system, 1 new instances...
azk: ✓ checking `azukiapp/node:0.12` image...
azk: ◴ waiting for `aguas-andinas` system to start, trying connection to port http/tcp...
azk: Run system `aguas-andinas` return: (0), for command: /bin/bash -c node server/app.js:
azk: [timeout] `azk` has timed out on `aguas-andinas` system.
azk: [timeout] Failure to reach port `49168` from `http://aguas-andinas.dev.azk.io` after 20 attempt[s] of 1000 milliseconds.
azk: [timeout] Make sure the start command binds `port` to the `0.0.0.0` interface, not only to the `localhost` interface.
azk: [timeout] You might want to edit your `Azkfile.js` in order to increase the maximum timeout.
azk: Due to the above error azk will stop all instances already running.

azk: ↓ stopping `aguas-andinas` system, 1 instances...
azk: ↓ stopping `mongodb` system, 1 instances...

┌───────────────┬───────┬──────────────────────────────────┬─────────────────┐
│ System        │ Inst. │ Hostname/url                     │ Instances-Ports │
├───────────────┼───────┼──────────────────────────────────┼─────────────────┤
│ aguas-andinas │ 0     │ aguas-andinas.dev.azk.io         │ -               │
├───────────────┼───────┼──────────────────────────────────┼─────────────────┤
│ mongodb       │ 0     │ aguas-andinas-mongodb.dev.azk.io │ -               │
└───────────────┴───────┴──────────────────────────────────┴─────────────────┘
```

**Comment by gullitmiranda** [comment]
Ensure that your application is up to the correct port and allowing external access.

```javascript
var http = require('http');
var PORT = process.env.HTTP_PORT || 3000;

var server = http.createServer(function (req, res) {
  // ...
});

server.listen(PORT);
console.log('Server running at http://0.0.0.0:' + PORT + '/');
```

In [Set up node so it is externally visible?](http://stackoverflow.com/a/18024792) You can have a more complete explanation.

You can also send your questions in our support chat which is the https://gitter.im/azukiapp/azk. Including call me in private.

**Comment by leonciokof** [comment]
The error was that not using the variable HTTP_PORT

Thank you very much for the help and time

**Comment by gullitmiranda** [comment]
:+1:
