### ISSUE TITLE
Error after upgrade to 0.12

### ISSUE THREAD

**Issue by lcsbaroni** [azukiapp/azk#366]
After updated azk to version 0.12, I get this error when run azk agent start:
/usr/local/Cellar/azk/0.12.0/.dependencies: No such file or directory

I created this file and now it works.

**Comment by nuxlli** [comment]
@lcsbaroni sorry, made a mistake when updating the installation of the formula "azk" on Mac OS X em https://github.com/azukiapp/homebrew-azk, the error has been corrected, to solve the problem on your machine do:

```
rm /usr/local/Cellar/azk/0.12.0/.dependencies
brew remove azk
brew untap azukiapp/azk
brew install azukiapp/azk/azk
```

Let us know if everything went well, and thanks for the quick warning about the error.

**Comment by lcsbaroni** [comment]
No problem @nuxlli, I delete azk from cache and installed again following your instructions, but I got a new error:
```bash
$ azk agent start
azk: Wait, this process may take several minutes
azk: Loading settings and checking dependencies.
azk: Checking version...
azk: Settings loaded successfully.
azk: Removing virtual machine...
azk: Virtual machine has been successfully removed.
azk: Agent is being started...
azk: Installing virtual machine...
azk: Agent starting error: Error: command: storageattach azk-vm-dev.azk.io --storagectl SATA --port 0 --device 0 --type dvddrive --medium /usr/local/Cellar/azk/0.12.0/lib/vm/0.1.0/azk.iso
azk: VBoxManage: error: Could not find file for the medium '/usr/local/Cellar/azk/0.12.0/lib/vm/0.1.0/azk.iso' (VERR_FILE_NOT_FOUND)
azk: VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Medium, interface IMedium, callee nsISupports
azk: VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
azk: VBoxManage: error: Invalid UUID or filename "/usr/local/Cellar/azk/0.12.0/lib/vm/0.1.0/azk.iso"
azk:     at /azk:0.12.0/src/agent/vm.js:19:13
azk: From previous event:
azk:     at exec (/azk:0.12.0/src/agent/vm.js:16:25)
azk:     at callee$1$0$ (/azk:0.12.0/src/agent/vm.js:237:16)
azk:     at tryCatch (/usr/local/Cellar/azk/0.12.0/node_modules/babel-runtime/regenerator/runtime.js:60:40)
azk:     at GeneratorFunctionPrototype.invoke (/usr/local/Cellar/azk/0.12.0/node_modules/babel-runtime/regenerator/runtime.js:205:22).
azk: Agent is being stopped...
azk: Agent has been successfully stopped.
```
Thanks for your quickly answer.

**Comment by nuxlli** [comment]
What unhappiness, as we provide new fixes to apply:

```
brew remove azk
rm /Library/Caches/Homebrew/azk-0.12.0.tar.gz
brew untap azukiapp/azk
brew install azukiapp/azk/azk
```

**Comment by lcsbaroni** [comment]
Now the agent start properly! Thanks

**Comment by heitortsergent** [comment]
Thanks for helping us find these errors @lcsbaroni :D

**Comment by lcsbaroni** [comment]
You are welcome!
