### ISSUE TITLE
error: TimeoutError when stopping elasticsearch

### ISSUE THREAD

**Issue by tinogomes** [azukiapp/azk#390]
```
$ azk stop elasticsearch
azk: ↓ stopping `elasticsearch` system, 1 instances...
error: TimeoutError: operation timed out
    at afterTimeout (/usr/local/Cellar/azk/0.12.1/node_modules/insight-keen-io/node_modules/bluebird/js/main/timers.js:11:15)
    at [object Object].timeoutTimeout (/usr/local/Cellar/azk/0.12.1/node_modules/insight-keen-io/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
error: TimeoutError: operation timed out
    at afterTimeout (/usr/local/Cellar/azk/0.12.1/node_modules/insight-keen-io/node_modules/bluebird/js/main/timers.js:11:15)
    at [object Object].timeoutTimeout (/usr/local/Cellar/azk/0.12.1/node_modules/insight-keen-io/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

┌───┬───────────────┬───────────┬──────────────┬─────────────────┬─────────────┐
│   │ System        │ Instances │ Hostname/url │ Instances-Ports │ Provisioned │
├───┼───────────────┼───────────┼──────────────┼─────────────────┼─────────────┤
│ ↓ │ elasticsearch │ 0         │ dev.azk.io   │ -               │ -           │
└───┴───────────────┴───────────┴──────────────┴─────────────────┴─────────────┘
```

**Comment by fearenales** [comment]
@tinogomes this issue is caused by a timeout error while tracking an event from `azk`.
This stack trace should be replaced by a `log.info` message, allowing the user to know when this occurs but not showing the error message to the user by default.
