### ISSUE TITLE
Slow test fails on Docker 1.6 (docker_build_error.unexpected_error)

### ISSUE THREAD

**Issue by saitodisse** [azukiapp/azk#391]
This test is failing. Probably is an error because of docker version:

```
$ azk nvm gulp --grep="with a invalids Dockerfile's should raise error for a invalid image"

1) Azk docker module, image build @slow with a invalids Dockerfile's should raise error for a invalid image:

      AssertionError: expected 'docker_build_error.unexpected_error' to equal 'docker_build_error.server_error'
      + expected - actual

      +"docker_build_error.server_error"
      -"docker_build_error.unexpected_error"
      
      at /azk:0.12.1/spec/docker/build_spec.js:72:50
  From previous event:
      at Context.<anonymous> (/azk:0.12.1/spec/docker/build_spec.js:70:15)
```

docker info:
```
$ docker --version
Docker version 1.6.0, build 4749651

$ docker info
Containers: 2
Images: 22
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.781 GiB
Name: julio-P67A-UD3-B3
ID: XYZ5:IFYM:RTR4:MVNV:YRFU:U2OX:UT63:6NDJ:U5HY:RNZU:IUIP:BIWT
WARNING: No swap limit support
```

**Comment by nuxlli** [comment]
Closed by #417
