### ISSUE TITLE
Registry download error

### ISSUE THREAD

**Issue by heitortsergent** [azukiapp/azk#407]
azk version: 0.12.1

Running Eventick's application, there was an issue when downloading the Ruby image:

```
azk: ✓ completed download of `azukiapp/postgres:9.3`

azk: ◴ waiting for `postgres` system to start, trying connection to port data/tcp...
azk: ↑ starting `woodstock` system, 2 new instances...
azk: ✓ checking `azukiapp/ruby:2.2.2` image...
azk: ⇲ downloading `azukiapp/ruby:2.2.2` image...
azk: ⇲ comparing registry layers and local layers...
azk: TypeError: Cannot call method 'toString' of null
azk:     at Image.callee$2$0$ (/azk:0.12.1/src/images/index.js:101:24)
azk:     at tryCatch (/usr/local/Cellar/azk/0.12.1/node_modules/babel-runtime/regenerator/runtime.js:60:40)
azk:     at GeneratorFunctionPrototype.invoke (/usr/local/Cellar/azk/0.12.1/node_modules/babel-runtime/regenerator/runtime.js:205:22)
azk: From previous event:
azk:     at Object._onImmediate (/azk:0.12.1/src/utils/index.js:97:18)
azk:     at processImmediate [as _immediateCallback] (timers.js:354:15)
azk: Due to the above error azk will stop all instances already running.

azk: System `woodstock` not running
azk: ↓ stopping `postgres` system, 1 instances...
```

Checking the line, it was supposed to convert the err object to a String, then throw an error message.

**Comment by gullitmiranda** [comment]
What happens is that the error is coming with a null value, and this should not occur. It is a problem in the [docker-registry-downloader](https://github.com/azukiapp/docker-registry-downloader/).

But we can avoid this by checking the error value:
in line https://github.com/azukiapp/azk/blob/master/src/images/index.js#L101 change to:

```javascript
output = (err || '').toString();
```

**Comment by dynaum** [comment]
@marcelofraga have the same error with the 0.13.0 version.

```shell
azk: ↑ starting `poseidon` system, 1 new instances...
azk: ↑ starting `redis` system, 1 new instances...
azk: ✓ checking `dynaum/ruby-sqlite:latest` image...
azk: ⇲ downloading `dynaum/ruby-sqlite:latest` image...
azk: TypeError: Cannot call method 'toString' of null
azk:     at Image.callee$2$0$ (/azk:0.13.0/src/images/index.js:101:24)
azk:     at tryCatch (/usr/local/Cellar/azk/0.13.0/node_modules/babel-runtime/regenerator/runtime.js:60:40)
azk:     at GeneratorFunctionPrototype.invoke (/usr/local/Cellar/azk/0.13.0/node_modules/babel-runtime/regenerator/runtime.js:205:22)
azk: From previous event:
azk:     at Object._onImmediate (/azk:0.13.0/src/utils/index.js:96:18)
azk:     at processImmediate [as _immediateCallback] (timers.js:354:15)
azk: Due to the above error azk will stop all instances already running.

azk: System `poseidon` not running
```
