### ISSUE TITLE
Error on container start

### ISSUE THREAD

**Issue by dynaum** [azukiapp/azk#41]
Some times this error occurs when I try to run a shell command:

```shell
azk: Error: HTTP code is 500 which indicates error: server error - Cannot start container 595fe29500f6a2e83990634f5bde2090afc4f59d958aa4f83ac93ed8d19bc4b6: lstat /home/docker/files: stale NFS file handle
    at Modem.buildPayload (/Users/dynaum/.azk/node_modules/docker-modem/lib/modem.js:134:15)
    at IncomingMessage.<anonymous> (/Users/dynaum/.azk/node_modules/docker-modem/lib/modem.js:111:14)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
From previous event:
    at Container._.each.newClass.(anonymous function) [as start] (/Users/dynaum/.azk/src/utils/index.js:78:39)
    at Docker.<anonymous> (/Users/dynaum/.azk/src/docker/run.js:122:20)
    at eval (eval at <anonymous> (/Users/dynaum/.azk/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:460:32)
    at Object.eval (eval at <anonymous> (/Users/dynaum/.azk/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:396:23)
```

**Comment by lucasfais** [comment]
That is a problem in VirtualBox file sharing between host and guest machine. We are working on a definitive solution.

In the meantime, the workaround to that problem is to restart the azk agent when it happens.
