### ISSUE TITLE
Error when the VM do not exists

### ISSUE THREAD

**Issue by robsonpeixoto** [azukiapp/azk#418]
`OS`: Darwin updated.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
`azk version`: 0.13.0-beta1

Environment details: Using VirtualBox 4.3.28

Steps to Reproduce:
```
$ /Applications/VirtualBox.app/Contents/Resources/VirtualBoxVM.app/Contents/MacOS/VBoxManage list vms
"boot2docker-vm" {d45b91dc-5e05-4efb-a472-511df75165bf}
$ azk vm status
azk: Error
azk:     at new RequiredError (/azk:0.13.0-beta1/src/cmds/vm.js:11:20)
azk:     at VmCmd.require_installed (/azk:0.13.0-beta1/src/cmds/vm.js:21:13)
azk:     at VmCmd.require_running (/azk:0.13.0-beta1/src/cmds/vm.js:26:10)
azk:     at VmCmd.action_status (/azk:0.13.0-beta1/src/cmds/vm.js:89:10)
azk:     at VmCmd.callee$2$0$ (/azk:0.13.0-beta1/src/cmds/vm.js:43:45)
azk:     at tryCatch (/usr/local/Cellar/azk/v0.13.0-beta1/node_modules/babel-runtime/regenerator/runtime.js:60:40)
azk:     at GeneratorFunctionPrototype.invoke (/usr/local/Cellar/azk/v0.13.0-beta1/node_modules/babel-runtime/regenerator/runtime.js:205:22)
azk: From previous event:
azk:     at Object._onImmediate (/azk:0.13.0-beta1/src/utils/index.js:96:18)
azk:     at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by gullitmiranda** [comment]
This command is in error. What has been fixed in the PR #412, does not yet finalized.
your `agent` is starting normally?

**Comment by robsonpeixoto** [comment]
Steps to reproduce the error. Maybe after the `azk vm remove` should stop the agent.
```
$ azk agent status
azk: Agent is running...
$ azk vm status
azk: Virtual machine running.
$ azk vm remove
azk: Stopping virtual machine...
azk: Virtual machine has been successfully stopped.
azk: Removing virtual machine...
azk: Virtual machine has been successfully removed.
$ azk agent status
azk: Agent is running...
$ azk vm status
azk: Error
azk:     at new RequiredError (/azk:0.12.1/src/cmds/vm.js:10:20)
azk:     at VmCmd.require_installed (/azk:0.12.1/src/cmds/vm.js:20:13)
azk:     at VmCmd.require_running (/azk:0.12.1/src/cmds/vm.js:25:10)
azk:     at VmCmd.action_status (/azk:0.12.1/src/cmds/vm.js:89:10)
azk:     at VmCmd.callee$2$0$ (/azk:0.12.1/src/cmds/vm.js:42:45)
azk:     at tryCatch (/usr/local/Cellar/azk/0.12.1/node_modules/babel-runtime/regenerator/runtime.js:60:40)
azk:     at GeneratorFunctionPrototype.invoke (/usr/local/Cellar/azk/0.12.1/node_modules/babel-runtime/regenerator/runtime.js:205:22)
azk: From previous event:
azk:     at Object._onImmediate (/azk:0.12.1/src/utils/index.js:97:18)
azk:     at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by gullitmiranda** [comment]
It's what I imagined it. The command `azk vm status` was logical error. It was resolved in PR # 412.

Miha concern was that it was in the way you start the agent.
Thanks for the report @robsonpeixoto .
