### ISSUE TITLE
Agent starting error: Error: lost_internet_connection

### ISSUE THREAD

**Issue by joridos** [azukiapp/azk#442]
When I use `$ azk agent start`, I receive the error:
```bash
azk: Wait, this process may take several minutes
azk: Loading settings and checking dependencies.
azk: Checking version...
azk: azk 0.13.1 detected
azk: Clearing 0 lost containers
azk: Settings loaded successfully.
azk: Agent is being started...
azk: Trying to connect to docker (unix:///var/run/docker.sock) (1/10)...
azk: Starting azk dns service...


azk: Agent starting error: Error: lost_internet_connection
azk:     at Error (<anonymous>)
azk:     at LostInternetConnection.AzkError (/azk:0.13.1/src/utils/errors.js:25:29)
azk:     at new LostInternetConnection (/azk:0.13.1/src/utils/errors.js:48:36)
azk:     at Image.callee$2$0$ (/azk:0.13.1/src/images/index.js:102:17)
azk:     at tryCatch (/usr/lib/azk/node_modules/babel-runtime/regenerator/runtime.js:60:40)
azk:     at GeneratorFunctionPrototype.invoke (/usr/lib/azk/node_modules/babel-runtime/regenerator/runtime.js:205:22)
azk: From previous event:
azk:     at Object._onImmediate (/azk:0.13.1/src/utils/index.js:96:18)
azk:     at processImmediate [as _immediateCallback] (timers.js:354:15).
azk: Agent is being stopped...
azk: Agent has been successfully stopped.

```

My network is fine.

**Comment by gullitmiranda** [comment]
@joridos 
The moment the `azk` was downloading of the `dns service` container, hears a loss of connection with the api Docker Hub.

Try again, and let me know if it was the same problem.

**Comment by saitodisse** [comment]
I believe that with the changes we put on `docker-registry-downloader` the lost connection message is good now:

![image](https://cloud.githubusercontent.com/assets/155953/8234898/4075c55a-15b5-11e5-853d-506097c2e0fe.png)

**Comment by gullitmiranda** [comment]
:+1:

**Comment by joridos** [comment]
Cool :smile: :+1:
