### ISSUE TITLE
SyntaxError: Unexpected token @

### ISSUE THREAD

**Issue by agutoli** [azukiapp/azk#502]
Hi, I'm trying to start my azk env and I getting this error.

MacBook Pro (Retina, 15-inch, Mid 2015)
Node: 0.12.7
npm:2.12.1 

```
$ azk agent start
azk: Wait, this process may take several minutes
azk: Loading settings and checking dependencies.
azk: Checking version...
azk: azk 0.14.5 detected

/usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/lib/parse.js:97
      return JSON.parse("{" + line + "}");
                  ^
SyntaxError: Unexpected token @
    at Object.parse (native)
    at to_item (/usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/lib/parse.js:97:19)
    at Array.map (native)
    at Object.exports.machinereadable_list (/usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/lib/parse.js:99:30)
    at /usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/lib/machine.js:47:37
    at Object.callback (/usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/lib/command.js:72:16)
    at next (/usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/node_modules/async/lib/async.js:720:43)
    at /usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/node_modules/async/lib/async.js:24:16
    at ChildProcess.<anonymous> (/usr/local/Cellar/azk/0.14.5/node_modules/vboxmanage/lib/command.js:64:20)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

**Comment by gullitmiranda** [comment]
@agutoli 
You are using VirtualBox 5.0, right?

This problem was corrected in #495, but has not yet released a version with it.

**Comment by agutoli** [comment]
Yes @gullitmiranda , I'm using the 5.0.2. I will try to use a 4.x version. tks!

**Comment by agutoli** [comment]
Hey @gullitmiranda , with Virtualbox 4.x works for me!... awesome!

**Comment by gullitmiranda** [comment]
nice
