### ISSUE TITLE
Error starting userland proxy

### ISSUE THREAD

**Issue by gullitmiranda** [azukiapp/azk#562]
If the docker change of IP is possible can be conflicts in libnss-resolver on Linux.

You need to make it better, it may be necessary to change [`src/agent/configure.js`](https://github.com/azukiapp/azk/blob/master/src/agent/configure.js), so it can cope with this change.
issue reported in: https://gitter.im/azukiapp/azk/pt?at=563b3f3d5680530d27049390 (pt-BR)

**Comment by slobo** [comment]
For me this happened:
On ubuntu 14 we ran `apt-get dist-upgrade` which brought azk from 0.15 to 0.16.1 and docker to 1.9. Trying to start azk did this:
```
$ azk agent start
...
azk: Starting azk dns service...
azk: Error: HTTP code is 500 which indicates error: server error - Cannot start container 4efbd5f4bfff9e5be91ad2686df06d4cfb15f3869cb1f61c5e053423c189641d: failed to create endpoint dev.azk.io_type.daemon_mid.ce833fc9c9_sys.dns_seq.1_uid.f6967a908a on network bridge: Error starting userland proxy: listen udp 172.17.42.1:53: bind: cannot assign requested address
...
$ azk doctor
azk: Error: Config docker:host to be set by configure
azk:     at Object.get (/azk:0.16.1/src/config.js:246:11)
azk:     at Object.module.exports.Object.defineProperties.default.get [as default] (/azk:0.16.1/src/docker/index.js:1:10)
azk:     at Doctor._createClass.get (/azk:0.16.1/src/cmds/doctor.js:13:33)
azk:     at Doctor.callee$2$0$ (/azk:0.16.1/src/cmds/doctor.js:30:82)
azk:     at tryCatch (/usr/lib/azk/node_modules/babel-runtime/regenerator/runtime.js:65:40)
azk:     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/azk/node_modules/babel-runtime/regenerator/runtime.js:229:22)
azk:     at GeneratorFunctionPrototype.Gp.(anonymous function) [as next] (/usr/lib/azk/node_modules/babel-runtime/regenerator/runtime.js:262:19)
azk:     at GeneratorFunctionPrototype.tryCatcher (/usr/lib/azk/node_modules/bluebird/js/main/util.js:24:31)
azk:     at PromiseSpawn._next (/usr/lib/azk/node_modules/bluebird/js/main/generators.js:100:49)
azk:     at Promise._settlePromiseAt (/usr/lib/azk/node_modules/bluebird/js/main/promise.js:528:21)
azk:     at Promise._settlePromiseAtPostResolution (/usr/lib/azk/node_modules/bluebird/js/main/promise.js:224:10)
azk:     at Async._drainQueue (/usr/lib/azk/node_modules/bluebird/js/main/async.js:182:12)
azk:     at Async._drainQueues (/usr/lib/azk/node_modules/bluebird/js/main/async.js:187:10)
azk:     at Async.drainQueues (/usr/lib/azk/node_modules/bluebird/js/main/async.js:15:14)
azk:     at process._tickCallback (node.js:442:13)
azk:     at Function.Module.runMain (module.js:499:11)
```

Note that also there were azktcl images left in created state
```
$ docker ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED              STATUS              PORTS               NAMES
28b9226a44af        azukiapp/azktcl:0.0.2   "/bin/bash -c 'dnsmas"   About a minute ago   Created                                 dev.azk.io_type.daemon_mid.ce833fc9c9_sys.dns_seq.1_uid.407686f08a
4efbd5f4bfff        azukiapp/azktcl:0.0.2   "/bin/bash -c 'dnsmas"   3 minutes ago        Created                                 dev.azk.io_type.daemon_mid.ce833fc9c9_sys.dns_seq.1_uid.f6967a908a
6ca5b2a97c42        azukiapp/azktcl:0.0.2   "/bin/bash -c 'dnsmas"   9 minutes ago        Created                                 dev.azk.io_type.daemon_mid.ce833fc9c9_sys.dns_seq.1_uid.137f8f808a
```

This all cleared up by following @gullitmiranda suggestion to  `rm -rf /etc/resolver/dev.azk.io` (and other custom domains we had in there).
