### ISSUE TITLE
[OSX, Agent] Not starting

### ISSUE THREAD

**Issue by SomeoneWeird** [azukiapp/azk#687]
1. What are you trying do accomplish?

Start agent

2. Steps to reproduce the described behavior

`azk agent start`

3. Output

https://gist.github.com/SomeoneWeird/65504ff04ef26248e2db67a754b8c34b

4. Further info

Reinstalled etc, no change

a. Which OS / distro?

Latest OSX.

```
➜  /tmp azk version --full
Version   : azk version 0.18.0, build 8b9f66c, date 2016-04-06
OS        : OS X (x64), Memory: 16384MB
Agent     : Stopped
Docker    : Down
Uses VM   : Yes
VirtualBox: 5.1.2r108956
```

b. Which VirtualBox version? (If running Mac OS X)

See above.

c. Can you provide us your Azkfile.js?

N/A

5. Do you have any suggestions on how to tackle this?

On `return JSON.parse("{" + line + "}");` it looks like `line` is `{"vrdeproperty[TCP/Address]":<not set>}` which obviously won't parse as valid JSON. 

Replacing `<not set>` with `null` gets further, but still generic failure error:

```
➜  /tmp azk agent start
azk: Please wait, this process may take several minutes
azk: Loading settings and checking dependencies.
azk: Checking version...
azk: azk 0.18.0 detected
azk: Settings loaded successfully.
azk: Removing virtual machine...
azk: Agent is being started...
azk: Starting virtual machine...
azk: Error: cannot start azk-vm-dev.azk.io
azk:     at /usr/local/Cellar/azk/0.18.0/node_modules/vboxmanage/lib/instance.js:45:25
azk:     at Object.callback (/usr/local/Cellar/azk/0.18.0/node_modules/vboxmanage/lib/command.js:72:16)
azk:     at next (/usr/local/Cellar/azk/0.18.0/node_modules/vboxmanage/node_modules/async/lib/async.js:720:43)
azk:     at /usr/local/Cellar/azk/0.18.0/node_modules/vboxmanage/node_modules/async/lib/async.js:24:16
azk:     at ChildProcess.<anonymous> (/usr/local/Cellar/azk/0.18.0/node_modules/vboxmanage/lib/command.js:64:20)
azk:     at ChildProcess.emit (events.js:98:17)
azk:     at maybeClose (child_process.js:766:16)
azk:     at Socket.<anonymous> (child_process.js:979:11)
azk:     at Socket.emit (events.js:95:17)
azk:     at Pipe.close (net.js:466:12)
azk: Sorry, an error has occurred.
azk: A crash report about this error will be sent to azk team in order to make azk better.
azk: Sending bug report to Azuki...
azk: Bug report was sent. Thanks.
azk: Agent is being stopped...
azk: Agent has been successfully stopped.
```

**Comment by SomeoneWeird** [comment]
This is still an issue with the latest version
