### ISSUE TITLE
agent start not working

### ISSUE THREAD

**Issue by chomman** [azukiapp/azk#702]
1. What are you trying do accomplish?

I execute `azk agent start`. But error..

2. Steps to reproduce the described behavior

[Give us enough data to reproduce this scenario]

3. Output

```
azk: Settings loaded successfully.
azk: Agent is being started...
azk: Installing virtual machine...
azk: Virtual machine has been successfully installed.
error: uncaughtException: Unexpected token x
{ date: 'Sun Nov 05 2017 00:28:52 GMT+0900 (KST)',
  process:
   { pid: 5972,
     uid: 501,
     gid: 20,
     cwd: '/usr/local/Cellar/azk/0.19.0',
     execPath: '/usr/local/Cellar/azk/0.19.0/lib/nvm/v0.10.40/bin/node',
     version: 'v0.10.40',
     argv:
      [ '/usr/local/Cellar/azk/0.19.0/lib/nvm/v0.10.40/bin/node',
        '/usr/local/Cellar/azk/0.19.0/bin/azk.js',
        '--no-daemon',
        'agent',
        'start',
        '--configure',
        '/Users/general/.azk/data/run/agent.json' ],
     memoryUsage:
      { rss: 138166272,
        heapTotal: 62339584,
        heapUsed: 28224720 } },
  os:
   { loadavg:
      [ 1.6904296875,
        1.52490234375,
        1.544921875 ],
     uptime: 5151 },
  trace:
   [ { column: null,
       file: null,
       function: 'Object.parse',
       line: null,
       method: 'parse',
       native: true },
     { column: 19,
       file: '/usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/lib/parse.js',
       function: 'to_item',
       line: 97,
       method: null,
       native: false },
     { column: null,
       file: null,
       function: 'Array.map',
       line: null,
       method: 'map',
       native: true },
     { column: 30,
       file: '/usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/lib/parse.js',
       function: 'Object.exports.machinereadable_list',
       line: 99,
       method: 'exports.machinereadable_list',
       native: false },
     { column: 37,
       file: '/usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/lib/machine.js',
       function: null,
       line: 47,
       method: null,
       native: false },
     { column: 16,
       file: '/usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/lib/command.js',
       function: 'Object.callback',
       line: 72,
       method: 'callback',
       native: false },
     { column: 43,
       file: '/usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/node_modules/async/lib/async.js',
       function: 'next',
       line: 720,
       method: null,
       native: false },
     { column: 16,
       file: '/usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/node_modules/async/lib/async.js',
       function: null,
       line: 24,
       method: null,
       native: false },
     { column: 20,
       file: '/usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/lib/command.js',
       function: '',
       line: 64,
       method: null,
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'ChildProcess.emit',
       line: 98,
       method: 'emit',
       native: false },
     { column: 16,
       file: 'child_process.js',
       function: 'maybeClose',
       line: 766,
       method: null,
       native: false },
     { column: 11,
       file: 'child_process.js',
       function: '',
       line: 979,
       method: null,
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'Socket.emit',
       line: 95,
       method: 'emit',
       native: false },
     { column: 12,
       file: 'net.js',
       function: 'Pipe.close',
       line: 466,
       method: 'close',
       native: false } ],
  stack:
   [ 'SyntaxError: Unexpected token x',
     '    at Object.parse (native)',
     '    at to_item (/usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/lib/parse.js:97:19)',
     '    at Array.map (native)',
     '    at Object.exports.machinereadable_list (/usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/lib/parse.js:99:30)',
     '    at /usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/lib/machine.js:47:37',
     '    at Object.callback (/usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/lib/command.js:72:16)',
     '    at next (/usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/node_modules/async/lib/async.js:720:43)',
     '    at /usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/node_modules/async/lib/async.js:24:16',
     '    at ChildProcess.<anonymous> (/usr/local/Cellar/azk/0.19.0/node_modules/vboxmanage/lib/command.js:64:20)',
     '    at ChildProcess.emit (events.js:98:17)',
     '    at maybeClose (child_process.js:766:16)',
     '    at Socket.<anonymous> (child_process.js:979:11)',
     '    at Socket.emit (events.js:95:17)',
     '    at Pipe.close (net.js:466:12)' ] }
```

4. Further info

a. Which OS / distro? MacOS Sierra
b. Which VirtualBox version? (If running Mac OS X) 5.2.0r118431
c. Can you provide us your Azkfile.js? no Azkfile.js file. Only start agent..

Version   : azk version 0.19.0, build 5db206d, date 2016-09-24
OS        : OS X (x64), Memory: 4096MB
Agent     : Stopped
Docker    : Down
Uses VM   : Yes
VirtualBox: 5.2.0r118431

**Comment by slobo** [comment]
I have a fix for VBox 5.2 in my repo: https://github.com/slobo/azk
